#!/usr/bin/env bash
# mac-inventory.sh - document the Mac host for hardened-k8s
#
# Produces two files:
#   PUBLIC  <outdir>/host.md                         safe to commit (no serials, IPs, hostnames, usernames)
#   PRIVATE ~/mac-inventory-<date>-private.txt       full detail, chmod 600, never commit
#
# Usage: ./scripts/mac-inventory.sh [outdir]   (default outdir: ./docs)
# No sudo required. Compatible with macOS's built-in bash 3.2.
set -uo pipefail

[[ "$(uname -s)" == "Darwin" ]] || { echo "This script is for macOS." >&2; exit 1; }

OUTDIR="${1:-./docs}"
STAMP="$(date +%Y%m%d-%H%M)"
PUBLIC="$OUTDIR/host.md"
PRIVATE="$HOME/mac-inventory-$STAMP-private.txt"
UTMCTL="/Applications/UTM.app/Contents/MacOS/utmctl"
UTM_DOCS="$HOME/Library/Containers/com.utmapp.UTM/Data/Documents"
mkdir -p "$OUTDIR"

# ---------- helpers ----------
ver() {  # ver <cmd> [args...] -> first line of version output, or "not installed"
  command -v "$1" >/dev/null 2>&1 || { echo "not installed"; return; }
  "$@" 2>&1 | head -1
}
vnum() {  # vnum <cmd> [args...] -> bare version number (handles multi-line/colored output)
  command -v "$1" >/dev/null 2>&1 || { echo "not installed"; return; }
  NO_COLOR=1 "$@" 2>&1 | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1
}
plist() { /usr/libexec/PlistBuddy -c "Print :$2" "$1" 2>/dev/null || echo "n/a"; }
listening() { netstat -an -p tcp 2>/dev/null | grep -qE "\.$1 .*LISTEN" && echo "listening" || echo "off"; }
section() { printf '\n===== %s =====\n' "$1"; }
run() { printf '$ %s\n' "$*"; eval "$*" 2>&1; echo; }

# ---------- facts used by both reports ----------
MODEL="$(sysctl -n hw.model)"
CHIP="$(sysctl -n machdep.cpu.brand_string)"
PCORES="$(sysctl -n hw.perflevel0.physicalcpu 2>/dev/null || echo '?')"
ECORES="$(sysctl -n hw.perflevel1.physicalcpu 2>/dev/null || echo '?')"
MEM_GB="$(( $(sysctl -n hw.memsize) / 1073741824 ))"
DISK="$(diskutil info / | awk -F: '/Container Total Space|Disk Size/ {sub(/^ +/,"",$2); print $2; exit}' | cut -d'(' -f1 | sed 's/ *$//')"
OS="$(sw_vers -productName) $(sw_vers -productVersion) ($(sw_vers -buildVersion))"

FILEVAULT="$(fdesetup status | head -1 | sed -E 's/^FileVault is //; s/\.$//')"
SIP="$(csrutil status 2>/dev/null | sed -E 's/System Integrity Protection status: //; s/\.$//')"
GATEKEEPER="$(spctl --status 2>/dev/null)"
FW="/usr/libexec/ApplicationFirewall/socketfilterfw"
FIREWALL="$($FW --getglobalstate 2>/dev/null | sed -E 's/^Firewall is //; s/ ?\(State = [0-9]+\)//; s/\.$//')"
STEALTH="$($FW --getstealthmode 2>/dev/null | sed 's/^Firewall stealth mode is //')"
SSH_STATE="$(listening 22)"
VNC_STATE="$(listening 5900)"

# ---------- PUBLIC summary ----------
{
  echo "# Host system"
  echo
  echo "Generated by \`scripts/mac-inventory.sh\` on $(date +%Y-%m-%d). Identifiers, network"
  echo "details, and account names are intentionally omitted."
  echo
  echo "## Hardware and OS"
  echo "| Item | Value |"
  echo "|---|---|"
  echo "| Model | $MODEL |"
  echo "| Chip | $CHIP ($PCORES performance + $ECORES efficiency cores) |"
  echo "| Memory | ${MEM_GB} GB unified |"
  echo "| Storage | $DISK |"
  echo "| OS | $OS |"
  echo
  echo "## Security posture"
  echo "| Control | State |"
  echo "|---|---|"
  echo "| FileVault | $FILEVAULT |"
  echo "| System Integrity Protection | $SIP |"
  echo "| Gatekeeper | $GATEKEEPER |"
  echo "| Application firewall | $FIREWALL |"
  echo "| Firewall stealth mode | $STEALTH |"
  echo "| Remote Login (SSH, port 22) | $SSH_STATE |"
  echo "| Screen Sharing (port 5900) | $VNC_STATE |"
  echo
  echo "## Toolchain"
  echo "| Tool | Version |"
  echo "|---|---|"
  echo "| Homebrew | $(ver brew --version) |"
  echo "| Ansible | $(ver ansible --version | sed 's/[][]//g') |"
  echo "| ansible-lint | $(vnum ansible-lint --version) |"
  echo "| Git | $(ver git --version) |"
  echo "| GitHub CLI | $(ver gh --version) |"
  echo "| Python | $(ver python3 --version) |"
  echo "| Terraform | $(ver terraform version) |"
  echo "| kubectl | $(ver kubectl version --client) |"
  echo "| tmux | $(ver tmux -V) |"
  if command -v brew >/dev/null 2>&1; then
    echo
    echo "Homebrew: $(brew list --formula | wc -l | tr -d ' ') formulae, $(brew list --cask | wc -l | tr -d ' ') casks installed."
  fi
  echo
  echo "## Virtual machines (UTM)"
  if [[ -d "$UTM_DOCS" ]]; then
    echo "| VM | Backend | Architecture | vCPU | Memory |"
    echo "|---|---|---|---|---|"
    for vm in "$UTM_DOCS"/*.utm; do
      [[ -e "$vm/config.plist" ]] || continue
      cfg="$vm/config.plist"
      cpu="$(plist "$cfg" System:CPUCount)"; [[ "$cpu" == "0" ]] && cpu="default"
      mem="$(plist "$cfg" System:MemorySize)"; [[ "$mem" =~ ^[0-9]+$ ]] && mem="$(( mem / 1024 )) GB"
      echo "| $(basename "$vm" .utm) | $(plist "$cfg" Backend) | $(plist "$cfg" System:Architecture) | $cpu | $mem |"
    done
  else
    echo "UTM not found."
  fi
} > "$PUBLIC"

# ---------- PRIVATE full report ----------
umask 077
{
  section "SYSTEM"
  run hostname
  run sw_vers
  run uname -a
  run system_profiler SPHardwareDataType
  run "diskutil list"
  run "df -h /"

  section "NETWORK"
  run "ifconfig | grep -E '^[a-z]|inet |ether '"
  run "networksetup -listallhardwareports"
  run "scutil --dns | grep nameserver | sort -u"

  section "SECURITY"
  run fdesetup status
  run csrutil status
  run spctl --status
  run "$FW --getglobalstate"
  run "$FW --getstealthmode"
  run "$FW --getallowsigned"
  run "netstat -an -p tcp | grep LISTEN"
  run "profiles status -type enrollment"

  section "HOMEBREW"
  run "brew --version"
  run "brew leaves | sort"
  run "brew list --cask | sort"

  section "DEV TOOLING"
  for t in "ansible --version" "ansible-lint --version" "git --version" "gh --version" \
           "python3 --version" "terraform version" "kubectl version --client" "tmux -V"; do
    run "$t"
  done
  run "ls ~/.ssh/*.pub"

  section "UTM VIRTUAL MACHINES"
  [[ -x "$UTMCTL" ]] && run "$UTMCTL list"
  for vm in "$UTM_DOCS"/*.utm; do
    [[ -e "$vm/config.plist" ]] || continue
    echo "--- $(basename "$vm") ---"
    run "plutil -p '$vm/config.plist' | grep -E 'Architecture|CPUCount|MemorySize|Backend|Target|MacAddress|Mode'"
    run "du -sh '$vm/Data'"
  done
} > "$PRIVATE"

echo "Public summary : $PUBLIC   (review, then commit)"
echo "Private report : $PRIVATE   (chmod 600, never commit)"
